// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_28 = "CgkI_KKZoLgQEAIQHg"; // <GPGSID>
        public const string achievement_29 = "CgkI_KKZoLgQEAIQHw"; // <GPGSID>
        public const string achievement_18 = "CgkI_KKZoLgQEAIQFA"; // <GPGSID>
        public const string achievement_19 = "CgkI_KKZoLgQEAIQFQ"; // <GPGSID>
        public const string achievement = "CgkI_KKZoLgQEAIQAg"; // <GPGSID>
        public const string achievement_4 = "CgkI_KKZoLgQEAIQBQ"; // <GPGSID>
        public const string achievement_2 = "CgkI_KKZoLgQEAIQAw"; // <GPGSID>
        public const string achievement_3 = "CgkI_KKZoLgQEAIQBA"; // <GPGSID>
        public const string achievement_6 = "CgkI_KKZoLgQEAIQBw"; // <GPGSID>
        public const string achievement_7 = "CgkI_KKZoLgQEAIQCA"; // <GPGSID>
        public const string achievement_ = "CgkI_KKZoLgQEAIQEQ"; // <GPGSID>
        public const string achievement_5 = "CgkI_KKZoLgQEAIQBg"; // <GPGSID>
        public const string achievement_8 = "CgkI_KKZoLgQEAIQCQ"; // <GPGSID>
        public const string achievement_9 = "CgkI_KKZoLgQEAIQCg"; // <GPGSID>
        public const string achievement_27 = "CgkI_KKZoLgQEAIQHQ"; // <GPGSID>
        public const string achievement_24 = "CgkI_KKZoLgQEAIQGg"; // <GPGSID>
        public const string achievement_17 = "CgkI_KKZoLgQEAIQEw"; // <GPGSID>
        public const string achievement_25 = "CgkI_KKZoLgQEAIQGw"; // <GPGSID>
        public const string achievement_14 = "CgkI_KKZoLgQEAIQDw"; // <GPGSID>
        public const string achievement_15 = "CgkI_KKZoLgQEAIQEA"; // <GPGSID>
        public const string leaderboard_2 = "CgkI_KKZoLgQEAIQIQ"; // <GPGSID>
        public const string achievement_20 = "CgkI_KKZoLgQEAIQFg"; // <GPGSID>
        public const string achievement_21 = "CgkI_KKZoLgQEAIQFw"; // <GPGSID>
        public const string achievement_10 = "CgkI_KKZoLgQEAIQCw"; // <GPGSID>
        public const string achievement_26 = "CgkI_KKZoLgQEAIQHA"; // <GPGSID>
        public const string achievement_11 = "CgkI_KKZoLgQEAIQDA"; // <GPGSID>
        public const string leaderboard = "CgkI_KKZoLgQEAIQIA"; // <GPGSID>
        public const string achievement_16 = "CgkI_KKZoLgQEAIQEg"; // <GPGSID>
        public const string leaderboard_mmr = "CgkI_KKZoLgQEAIQAQ"; // <GPGSID>
        public const string achievement_22 = "CgkI_KKZoLgQEAIQGA"; // <GPGSID>
        public const string achievement_23 = "CgkI_KKZoLgQEAIQGQ"; // <GPGSID>
        public const string achievement_12 = "CgkI_KKZoLgQEAIQDQ"; // <GPGSID>
        public const string achievement_13 = "CgkI_KKZoLgQEAIQDg"; // <GPGSID>

}

