 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace Main
{
	public class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID RequestLogin = (Nettention.Proud.RmiID)1000+1;
			public const Nettention.Proud.RmiID NotifyLoginSuccess = (Nettention.Proud.RmiID)1000+2;
			public const Nettention.Proud.RmiID NotifyLoginFailed = (Nettention.Proud.RmiID)1000+3;
			public const Nettention.Proud.RmiID PvPMatchSuccess = (Nettention.Proud.RmiID)1000+4;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			RequestLogin,
			NotifyLoginSuccess,
			NotifyLoginFailed,
			PvPMatchSuccess,
		};
	}
}

				 
